language: node_js
node_js:
  - 4
  - 6
before_script:
  - npm install -g snyk
script: snyk test
notifications:
  email:
    recipients:
      - sre@apiary.io
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
